# Use OpenJDK 22 as base image
FROM openjdk:22-jdk-slim

# Set working directory inside container
WORKDIR /app

# Copy Maven wrapper and project files
COPY .mvn/ .mvn
COPY mvnw pom.xml ./
COPY src ./src

# Build the Spring Boot app
RUN ./mvnw clean package -DskipTests
# Give execute permission to Maven wrapper
RUN chmod +x mvnw
# Give execute permission to Maven wrapper


# Expose port 8080
EXPOSE 8080

# Run the jar
CMD ["java", "-jar", "target/*.jar"]
